name: Build
# 
on: 
    push:
        branches: ["main"]
    schedule:
      - cron: "* */8 * * *" # Every 8 hours

jobs:
  build-matlab-batch-image:
    uses: ./.github/workflows/action.yml
    with: 
      directory: "matlab-batch-image"
      name: "matlab-batch"

  build-matlab-proxy-image:
    uses: ./.github/workflows/action.yml
    with: 
      directory: "matlab-proxy-image"
      name: "matlab-proxy"

      # - name: Build image
      #   run: |
      #     cd matlab-batch-image
      #     docker build \
      #       -t ${{ secrets.DOCKERHUB_USERNAME }}/matlab-batch:latest \
      #       --build-arg MATLAB_RELEASE=r2024a \
      #       -t ${{ secrets.DOCKERHUB_USERNAME }}/matlab-batch:${{ steps.semver.outputs.next }} .


